version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    #depends_on:
    #  - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blog?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234